name: Data Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite
  workflow_dispatch:

# Adicionar permissões para permitir push
permissions:
  contents: write

jobs:
  download-and-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Importante para o git push funcionar

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download data
      run: |
        mkdir -p data/raw
        python scripts/download_data.py

    - name: RUN ETL and ML Training
      env:
        NEON_DB_URL: ${{ secrets.NEON_DB_URL }}
      run: |
        mkdir -p data/processed
        mkdir -p models
        
        # Executar ETL
        python scripts/etl_local.py
        
        # Treinar modelo
        python scripts/train_model.py

    - name: Commit processed data
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automático do GitHub
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/processed/*
        git add models/*
        git commit -m "Update processed data and models" || echo "No changes to commit"
        git push origin main  # Especificar o branch principal
