name: ETL Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 3AM UTC

jobs:
  run-etl:
    runs-on: ubuntu-latest
    env:
      NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run ETL and ML training
      run: |
        # Criar estrutura de diretórios
        mkdir -p data/raw
        mkdir -p data/processed
        mkdir -p models
        
        # Executar ETL (usando caminho absoluto)
        python $GITHUB_WORKSPACE/scripts/etl_local.py
        
        # Treinar modelo
        python $GITHUB_WORKSPACE/scripts/ml_train.py
        
    - name: Commit processed data and models
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/processed/*
        git add models/*
        git commit -m "Update processed data and models" || echo "No changes to commit"
        git push
